# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "0x90"
email: noemail4u@example.com
description: > # this means to ignore newlines until "baseurl:"
  "0x90" Zone (or NoOperation Zone). There is actually nothing to see here.
  This website is for my personal infosec research. Opinions are mine only.
  It's a blog, you can find some articles about what I get in the field.
  Constructive comments are welcome. Have fun, stay safe.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.0x90.zone" # the base hostname & protocol for your site
twitter_username: Pedro_SEC_R
github_username:  psrodrigues

# Build settings
markdown: kramdown
